spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/restaurant_app_database
    username: user
    password: password
  jpa:
    hibernate:
      # TODO make validate
      ddl-auto: update
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
    # TODO make true
  flyway:
    enabled: false
