spring:
#  h2:
#    console:
#   ## http://localhost:8080/h2-console
#      enabled: true
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/restaurant_app_database
    username: user
    password: password
#  datasource:
#    url: jdbc:h2:mem:testdb
#    driver-class-name: org.h2.Driver
#    username: sa
#    password: password
  jpa:
    hibernate:
      # TODO make validate
      ddl-auto: update
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
#        dialect: org.hibernate.dialect.H2Dialect
    show-sql: true
    ## TODO make true
  flyway:
    enabled: false
  ## if enable uses the compose.yaml file to create dependant data sources
  docker:
    compose:
      enabled: false
